name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]  # Change this to your default branch if it's different
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: read  # Allow reading repository contents
  pages: write    # Allow writing to GitHub Pages
  id-token: write # Required for GitHub Pages deployment

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1  # Limit the checkout to the latest commit

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'  # Specify the Go version

      - name: Build static site
        run: |
          go mod init your-module-name  # Initialize Go module if not already done
          go get github.com/russross/blackfriday/v2  # Add the blackfriday dependency
          go build -o ssg  # Build the Go static site generator
          ./ssg  # Run the static site generator

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public  # Path to the directory containing your generated files

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
